POST http://localhost:8080/orders
Content-Type: application/json

{
  "orderId": "123",
  "itemId": "item-1",
  "quantity": 2
}

### List all orders

GET http://localhost:8080/orders

### Get a single order

GET http://localhost:8080/orders/123

### Delete an order

DELETE http://localhost:8080/orders/123
